### ISSUE TITLE
如何在 GitHub Workflows 中配置个人访问令牌（PAT）防止 403 错误

### ISSUE THREAD

**Issue by buxuele** [buxuele/my_hugo_blog#1]
## 问题背景
在使用 GitHub Actions 时，可能会遇到权限不足导致的 403 错误。这通常是因为默认的 `GITHUB_TOKEN` 权限限制或者 API 访问限制导致的。

### 1. 创建个人访问令牌（Personal Access Token）
1. 访问 GitHub 设置页面
   - 点击右上角头像
   - 选择 `Settings`
   - 滚动到底部，点击 `Developer settings`
   - 选择 `Personal access tokens` → `Tokens (classic)`
   - 点击 `Generate new token` → `Generate new token (classic)`

2. 配置令牌权限：
   - 为令牌设置一个描述性的名称（Note）
   - 选择令牌的有效期
   - 根据需求选择以下权限：
     - `repo` （完整的仓库访问权限）
     - `workflow` （如果需要操作 Actions）
     - 其他根据实际需要的权限

3. 生成并保存令牌
   - 点击 `Generate token`
   - **重要：** 立即复制并安全保存生成的令牌，因为它只会显示一次

### 2. 在仓库中添加密钥
1. 进入需要配置的仓库
2. 点击 `Settings` → `Secrets and variables` → `Actions`
3. 点击 `New repository secret`
4. 添加新密钥：
   - Name: `PAT` （或其他易记的名称）
   - Value: 粘贴之前生成的个人访问令牌
   - 点击 `Add secret`

### 3. 在 Workflow 中使用令牌
在你的 workflow 文件（`.github/workflows/xxx.yml`）中，可以通过以下方式使用令牌：

```yaml
name: Your Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # 使用配置的 PAT 替换默认的 GITHUB_TOKEN
          token: ${{ secrets.PAT }}
      
      # 在其他需要认证的步骤中也可以使用
      - name: Some Action
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
```

### 注意事项
1. **安全性：** 
   - 永远不要直接在代码中暴露令牌
   - 定期轮换令牌
   - 给予最小必要权限

2. **权限范围：**
   - 确保令牌具有必要的权限范围，但不要过度授权
   - 如果只需要特定仓库的访问权限，可以在生成令牌时限制范围

3. **调试：**
   - 如果遇到权限问题，检查令牌是否正确配置
   - 查看 Actions 日志中的错误信息
   - 确认令牌未过期

### 可能的问题排查
如果配置后仍然遇到问题：
1. 检查令牌是否具有足够的权限
2. 确认 secrets 是否正确配置在仓库中
3. 验证 workflow 文件中的语法是否正确
4. 检查令牌是否过期
